# .github/workflows/deploy-react.yml
name: Deploy React App

on:
  push:
    branches: [ "main" ]
    paths:
      - 'retirement-calculator/**'  # Only trigger on changes to React app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React
        run: |
          cd react-app
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: react-app/build
          branch: gh-pages